In [ ]:
import json
import numpy as np
import keras
import keras.preprocessing.text as kpt
from keras.preprocessing.text import Tokenizer
from keras.models import model_from_json
from keras.preprocessing.sequence import pad_sequences
import json
import keras
import pandas as pd
import keras.preprocessing.text as kpt
from keras.preprocessing.text import Tokenizer
import numpy as np
from sklearn.model_selection import train_test_split

from keras.models import Sequential
from keras.layers import Dense, LSTM, SimpleRNN, Dropout, Activation, Embedding
from datetime import datetime
from tensorflow.keras.callbacks import EarlyStopping

import matplotlib.pyplot as plt

from sklearn.metrics import confusion_matrix

import json
from keras.models import model_from_json

# Import libraries
import seaborn as sns
from sklearn.feature_extraction.text import CountVectorizer
import nltk 
# nltk.download()
import string
import re
%matplotlib inline
pd.set_option('display.max_colwidth', 100)

import string
import re

In [ ]:
# we're still going to use a Tokenizer here, but we don't need to fit it
tokenizer = Tokenizer(num_words=3000)
# for human-friendly printing
labels = ['fake', 'real']

# read in our saved dictionary
with open('./Dictionary_Models/word2vec_models_dictionary.json', 'r') as dictionary_file:
    dictionary = json.load(dictionary_file)

In [ ]:
# this utility makes sure that all the words in your input
# are registered in the dictionary
# before trying to turn them into a matrix.
def convert_text_to_index_array(text):
    words = kpt.text_to_word_sequence(text)
    wordIndices = []
    for word in words:
        if word in dictionary:
            wordIndices.append(dictionary[word])
        # else:
        #     print("'%s' not in training corpus; ignoring." %(word))
    return wordIndices

In [ ]:
# read in your saved model structure
json_file = open('./NN_Models/word2vec_BLSTM_model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
# and create a model from that
model = model_from_json(loaded_model_json)
# and weight your nodes with your saved values
model.load_weights('./NN_Models/word2vec_BLSTM_model.h5')


In [13]:

while 1:
    evalSentence =input('Input a sentence to be evaluated, or Enter to quit:')

    if len(evalSentence) == 0:
        break
        

    #### removing entries where location values are missing
#     data_after_null_removal = evalSentence

    #punctutation removal
    def clean_text(text):
        '''Make text lowercase, remove text in square brackets,remove links,remove punctuation
        and remove words containing numbers.'''
        text = text.lower()
        text = re.sub('\[.*?\]', '', text)
        text = re.sub('https?://\S+|www\.\S+', '', text)
        text = re.sub('<.*?>+', '', text)
        text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
        text = re.sub('\n', '', text)
        text = re.sub('\w*\d\w*', '', text)
        return text

#     data_afer_punctuation_removal = data_after_null_removal.copy()
#     data_afer_punctuation_removal['text'] = data_afer_punctuation_removal['text'].apply(lambda x: clean_text(x))
#     data_afer_punctuation_removal.head(10)
    
    data_afer_punctuation_removal = clean_text(evalSentence)

    # Tockenization

    def tokenization(text):
        text = re.split('\W+', text)
        return text

#     tockenized_data = data_afer_punctuation_removal.copy()
#     tockenized_data['text'] = tockenized_data['text'].apply(lambda x: tokenization(x.lower()))
    tockenized_data = tokenization(data_afer_punctuation_removal)

    # stopword removal 
#     data_after_stopword_removal = tockenized_data.copy()
    stopword = nltk.corpus.stopwords.words('english')

    def remove_stopwords(text):
        text = [word for word in text if word not in stopword]
        return text

#     data_after_stopword_removal['text'] = data_after_stopword_removal['text'].apply(lambda x: remove_stopwords(x))

    data_after_stopword_removal = remove_stopwords(tockenized_data)
    
    # return to string
#     data_without_tockenization = data_after_stopword_removal.copy()
    def listToString(s):     
        # initialize an empty string 
        str1 = " " 
        # return string   
        return (str1.join(s)) 

#     data_without_tockenization['text'] = data_without_tockenization['text'].apply(lambda x: listToString(x))
    data_without_tockenization = listToString(data_after_stopword_removal)
        
    from keras.preprocessing.text import Tokenizer
    from keras.preprocessing.sequence import pad_sequences

    tokenizer = Tokenizer(num_words=3000)

    X_train = tokenizer.texts_to_sequences(data_without_tockenization)
    
    max_length = 23
    X_train = pad_sequences(X_train, maxlen=max_length, padding='post')
        
        
#     max_length = 23
#     evalT = tokenizer.texts_to_sequences(data_without_tockenization)
#     print(evalT)
#     evalT = pad_sequences(evalT, maxlen=max_length, padding='post')
#     print(evalT)

    print(X_train)
    
    pred = model.predict(X_train)
 
    print(' sentiment: ', labels[np.argmax(pred)])
    

    
#     testArr = convert_text_to_index_array(evalSentence)
#     input = tokenizer.sequences_to_matrix(testArr, mode='binary')
#     # predict which bucket your input belongs in

# #     format your input for the neural net
#     testArr = convert_text_to_index_array(text1)
#     input = tokenizer.sequences_to_matrix([testArr], mode='binary')
    
#     pred = model.predict(input)
 
#     print(' sentiment: ', labels[np.argmax(pred)])
       

Input a sentence to be evaluated, or Enter to quit:there is a fire in the mountain
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
 sentiment:  fake
Input a sentence to be evaluated, or Enter to quit:
